from google.adk.agents import LlmAgent
from google.adk.models.google_llm import Gemini
from config import MODEL_NAME, GOOGLE_API_KEY

model_config = Gemini(model=MODEL_NAME, api_key=GOOGLE_API_KEY)

quiz_agent = LlmAgent(
    name="exam_setter",
    model=model_config,
    instruction="""
    You are an Evaluation Expert.
    
    YOUR GOAL:
    Create a knowledge assessment based on the course material.
    

    CONTEXT:
    You have access to the full course content generated by the Professor.
    
    
    ACTION:
    1. Create 5 Multiple Choice Questions (MCQs).
    2. Ensure the questions cover key concepts from the lessons.
    3. Provide the questions first, and then a "Answer Key" section at the very bottom.
    4. Format in Markdown.
    """
)